### ISSUE TITLE
Changing Parameters in Experiments

### ISSUE THREAD

**Issue by mayank0403** [pps-lab/rofl-project-code#4]
Hi,

I want to run the code with a large number of clients and L2 norm proofs. I tried using the "manual" method as described in the readme, but I am seeing a bug.
If I run the manual method with only 4 clients (as written in the readme), then the code runs fine, but increasing the number of clients to (say) 10 (`-n 10`) gives the following error:
```
Client 1 connects to trainer at port 50016
Client 2 connects to trainer at port 50016
Client 3 connects to trainer at port 50016
Client 4 connects to trainer at port 50016
Client 5 connects to trainer at port 50016
Client 6 connects to trainer at port 50016
Client 7 connects to trainer at port 50016
Client 8 connects to trainer at port 50016
Client 9 connects to trainer at port 50016
Client 0 connects to trainer at port 50016
[2022-08-03 23:24:11.249227 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 7 starts training model
[2022-08-03 23:24:11.250280 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 3 starts training model
[2022-08-03 23:24:11.250386 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 7 registers to train model 1
[2022-08-03 23:24:11.250544 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 3 registers to train model 1
[2022-08-03 23:24:11.250751 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 1 starts training model
[2022-08-03 23:24:11.250967 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 0 starts training model
[2022-08-03 23:24:11.251063 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 9 starts training model
[2022-08-03 23:24:11.251153 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 1 registers to train model 1
[2022-08-03 23:24:11.251281 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 6 starts training model
[2022-08-03 23:24:11.251402 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 2 starts training model
[2022-08-03 23:24:11.251541 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 5 starts training model
[2022-08-03 23:24:11.251653 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 2 registers to train model 1
[2022-08-03 23:24:11.251726 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 5 registers to train model 1
[2022-08-03 23:24:11.251868 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 8 starts training model
[2022-08-03 23:24:11.251981 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 9 registers to train model 1
[2022-08-03 23:24:11.252081 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 0 registers to train model 1
[2022-08-03 23:24:11.252179 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 6 registers to train model 1
[2022-08-03 23:24:11.252260 +00:00] INFO [rofl_service/src/flserver/client.rs:166] Client 4 starts training model
[2022-08-03 23:24:11.252349 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 8 registers to train model 1
[2022-08-03 23:24:11.252411 +00:00] INFO [rofl_service/src/flserver/client.rs:172] Client 4 registers to train model 1
[2022-08-03 23:24:11.262882 +00:00] INFO [rofl_service/src/flserver/client.rs:198] Client 2 starts protocol loop for model 1
[2022-08-03 23:24:11.262964 +00:00] INFO [rofl_service/src/flserver/client.rs:198] Client 0 starts protocol loop for model 1
[2022-08-03 23:24:11.263236 +00:00] INFO [rofl_service/src/flserver/client.rs:198] Client 5 starts protocol loop for model 1
[2022-08-03 23:24:11.263294 +00:00] INFO [rofl_service/src/flserver/client.rs:198] Client 6 starts protocol loop for model 1
[2022-08-03 23:24:11.264963 +00:00] INFO [rofl_service/src/flserver/client.rs:212] Client 0 receives model parameters for round 0
[2022-08-03 23:24:11.266393 +00:00] INFO [rofl_service/src/flserver/client.rs:212] Client 2 receives model parameters for round 0
[2022-08-03 23:24:11.266550 +00:00] INFO [rofl_service/src/flserver/client.rs:212] Client 6 receives model parameters for round 0
[2022-08-03 23:24:11.266869 +00:00] INFO [rofl_service/src/flserver/client.rs:212] Client 5 receives model parameters for round 0
[2022-08-03 23:24:11.266945 +00:00] INFO [rofl_service/src/flserver/client.rs:198] Client 9 starts protocol loop for model 1
[2022-08-03 23:24:11.267068 +00:00] INFO [rofl_service/src/flserver/client.rs:212] Client 9 receives model parameters for round 0
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', /home/ubuntu/rofl-project-code/rofl_service/src/flserver/client.rs:191:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', ', /home/ubuntu/rofl-project-code/rofl_service/src/flserver/client.rs/home/ubuntu/rofl-project-code/rofl_service/src/flserver/client.rs::thread '191191::1414

tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', /home/ubuntu/rofl-project-code/rofl_service/src/flserver/client.rs:191:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', /home/ubuntu/rofl-project-code/rofl_service/src/flserver/client.rs:191:14
```

The code still runs, but only with clients 0, 2, 5, 6 and 9. All other clients become dead it seems.

Moreover, is there a way to just benchmark the time it takes for the cryptography part (proof generation and communication on the client, and proof verification and aggregation on the server), i.e., ignoring all ML training?

**Comment by lisitian080516** [comment]
Hi,Have you solved the above problem?

**Comment by hiddely** [comment]
Hi Mayank,

Apologies for getting back to you so late. I would also be curious to know if the problem still occurs. What output does the server give you when the crash happens?

Regarding your question on the crypto part, you can run the microbenchmarks using the benches defined in [rofl_crypto/Cargo.toml](https://github.com/pps-lab/rofl-project-code/blob/master/rofl_crypto/Cargo.toml).

Let me know if you have any further questions. Cheers!
