### ISSUE TITLE
Error in trainservice/service.py

### ISSUE THREAD

**Issue by JiaweiWang-AdrianA** [pps-lab/rofl-project-code#7]
It seems to be an incorrect default value in row 14 of trainservice/service.py:
`parser.add_argument('--dataset_path', type=str, default='../configs/example_config.yml',
                    help='Path to local client dataset')`

When I run the `python trainservice/service.py`, an error happened:
```
Traceback (most recent call last):
  File "trainservice/service.py", line 42, in <module>
    client = AnalysisClientWrapper(args.config, args.dataset_path)
  File ".../rofl-project-code/rofl_train_client/trainservice/analysis_wrapper/analysis_client.py", line 23, in __init__
    self.dataset = load_dataset(dataset_path, batch_size, augment_data)
  File ".../rofl-project-code/rofl_train_client/trainservice/analysis_wrapper/data_loader.py", line 11, in load_dataset
    val = np.load(dataset_path, allow_pickle=True)
  File ".../lib/python3.7/site-packages/numpy/lib/npyio.py", line 463, in load
    "Failed to interpret file %s as a pickle" % repr(file))
OSError: Failed to interpret file '../configs/example_config.yml' as a pickle
```

**Comment by JiaweiWang-AdrianA** [comment]
I removed the comment from line 10 in trainservice/analysis_wrapper/data_loader.py:
```
def load_dataset(dataset_path, batch_size, augment_data) -> Dataset:

    return load_mnist_dummy()
```
Then, I successfully ran `python trainservice/service.py`. 
However, when I continued to run `./target/debug/flclients -n 5 -r 50016`, another error happened:
```
...
[2023-09-22 09:13:50.318927 +00:00] INFO [rofl_service/src/flserver/client.rs:195] Client 0 starts training model
[2023-09-22 09:13:50.319475 +00:00] INFO [rofl_service/src/flserver/client.rs:201] Client 0 registers to train model 1
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', .../rofl-project-code/rofl_service/src/flserver/client.rs:220:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', .../rofl-project-code/rofl_service/src/flserver/client.rs:220:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', .../rofl-project-code/rofl_service/src/flserver/client.rs:220:14
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }',.../rofl-project-code/rofl_service/src/flserver/client.rs:220:14
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Status { code: Cancelled, message: "h2 protocol error: stream error received: stream no longer needed" }', .../rofl-project-code/rofl_service/src/flserver/client.rs:220:14
```

**Comment by hiddely** [comment]
The client logs seem to indicate the server went offline. What do the server logs say?

**Comment by JiaweiWang-AdrianA** [comment]
server logs:
```
[2023-09-23 00:11:53.628291 +00:00] INFO [rofl_service/src/flserver/server.rs:574] Register Messages received from from client 2 for model 1
[2023-09-23 00:11:53.628809 +00:00] INFO [rofl_service/src/flserver/server.rs:598] Initialize model and broadcast it to clients
[2023-09-23 00:11:53.634434 +00:00] INFO [rofl_service/src/flserver/server.rs:602] First training round has started
[2023-09-23 00:11:53.637232 +00:00] INFO [rofl_service/src/flserver/server.rs:574] Register Messages received from from client 0 for model 1
thread 'tokio-runtime-worker' panicked at 'not yet implemented', rofl_service/src/flserver/server.rs:590:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2023-09-23 00:11:53.640785 +00:00] INFO [rofl_service/src/flserver/server.rs:574] Register Messages received from from client 3 for model 1
thread 'tokio-runtime-worker' panicked at 'not yet implemented', rofl_service/src/flserver/server.rs:590:13
[2023-09-23 00:11:53.644595 +00:00] INFO [rofl_service/src/flserver/server.rs:574] Register Messages received from from client 1 for model 1
thread 'tokio-runtime-worker' panicked at 'not yet implemented', rofl_service/src/flserver/server.rs:590:13
```

**Comment by hiddely** [comment]
The server is throwing an error because it is receiving a client registration request after training has already started. How many clients does the server expect to participate? The expectation of the server and the actual number of clients should be equal.

**Comment by JiaweiWang-AdrianA** [comment]
the logs of trainservice/service.py:

```
...
Config(environment=Environment(num_clients=20, num_selected_clients=10, num_malicious_clients=0, experiment_name='backdoor_tasks_noattack', num_selected_malicious_clients=None, malicious_client_indices=None, attack_frequency=None, attacker_full_dataset=False, attacker_full_knowledge=False, load_model=None, ignore_malicious_update=False, print_every=1, print_batch_text=False, save_updates=False, save_norms=False, save_weight_distributions=False, save_history=False, save_model_at=[], save_weight_outside_bound=None, print_backdoor_eval=False, seed=0, use_config_dir=True, limit_tf_gpu_mem_mb=None), server=Server(num_rounds=10, num_test_batches=25, federated_dropout=None, aggregator={'name': 'FedAvg'}, global_learning_rate=1.0, intrinsic_dimension=1000, gaussian_noise=0.0), client=ClientConfig(model_name='dev', benign_training=TrainingConfig(num_epochs=5, batch_size=32, learning_rate=0.01, decay=None, optimizer='SGD', regularization_rate=None), quantization=None, malicious=None, optimized_training=True, gaussian_noise=None, clip=None, model_weight_regularization=None, debug_client_training=False, disable_bn=False), dataset=Dataset(dataset='mnist', data_distribution='IID', number_of_samples=-1, augment_data=False, normalize_mnist_data=False), hyperparameters=None)
...
2023-09-25 04:45:54,765 - root - INFO - Training round 0
```
and I changed the command to run client, such as `./target/debug/flclients -n 4 -r 50016`, `./target/debug/flclients -n 10 -r 50016` or `./target/debug/flclients -n 20 -r 50016`. The above commands all result in similar ERRORs.

**Comment by hiddely** [comment]
You also have to make sure the server expects the right number of clients specified in `environment.num_clients` in the YAML config (for the `config_server` executable). If you are using the `flserver` executable, the number of clients is hardcoded, and is currently set to `1`. You can change that [here](https://github.com/pps-lab/rofl-project-code/blob/c1a0c13af4fb15b5c2ac9e0ca31d8623c0b0ee9b/rofl_service/src/bin/basic_server.rs#L87C37-L87C37). I hope this helps!

**Comment by JiaweiWang-AdrianA** [comment]
Thanks! It worked!
